'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ApplicationSetting
    Public Property ApplicationSettingId As Integer
    Public Property TenantID As System.Guid
    Public Property ApplicationSettingKey As String
    Public Property ApplicationSettingDesc As String
    Public Property ApplicationSettingValue As String
    Public Property CreatedOnUTC As Date

End Class
