'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CheckinSource
    Public Property CheckInSourceId As Integer
    Public Property CheckInSource1 As String

    Public Overridable Property FileVersions As ICollection(Of FileVersion) = New HashSet(Of FileVersion)

End Class
