'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileAgent
    Public Property FileAgentId As System.Guid
    Public Property TenantID As System.Guid
    Public Property AgentName As String
    Public Property SecretKey As String
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)

    Public Overridable Property WorkSpaces As ICollection(Of WorkSpace) = New HashSet(Of WorkSpace)
    Public Overridable Property FileAgentShares As ICollection(Of FileAgentShare) = New HashSet(Of FileAgentShare)

End Class
