'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileShareDir
    Public Property FileShareDirID As Integer
    Public Property TenantID As System.Guid
    Public Property FileShareID As Nullable(Of Integer)
    Public Property DirType As String
    Public Property PIDUnitType1 As String
    Public Property PIDUnitType2 As String
    Public Property PIDUnitType3 As String
    Public Property RelativePath As String
    Public Property RelativePathHash As String
    Public Property AllowWOTStd As String
    Public Property AllowWOTPIDU As Nullable(Of Boolean)
    Public Property ObsoleteDirName As String
    Public Property Description As String
    Public Property ForProjects As Nullable(Of Boolean)

    Public Overridable Property FileShare As FileShare

End Class
