'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileEntryDeleteGroupHierarchy
    Public Property FileEntryDeleteGroupHierarchyId As System.Guid
    Public Property TenantID As System.Guid
    Public Property FileEntryDeleteGroupId As System.Guid
    Public Property FileEntryId As System.Guid
    Public Property ParentFileEntryId As System.Guid

    Public Overridable Property FileEntry As FileEntry
    Public Overridable Property FileEntry1 As FileEntry
    Public Overridable Property FileEntryDeleteGroup As FileEntryDeleteGroup

End Class
