'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FileMinisterEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FileMinisterEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ApplicationSettings() As DbSet(Of ApplicationSetting)
    Public Overridable Property FileAgents() As DbSet(Of FileAgent)
    Public Overridable Property FileAgentShares() As DbSet(Of FileAgentShare)
    Public Overridable Property FileEntries() As DbSet(Of FileEntry)
    Public Overridable Property FileEntryLinks() As DbSet(Of FileEntryLink)
    Public Overridable Property FileEntryTypes() As DbSet(Of FileEntryType)
    Public Overridable Property FileShares() As DbSet(Of FileShare)
    Public Overridable Property FileVersions() As DbSet(Of FileVersion)
    Public Overridable Property FileVersionConflicts() As DbSet(Of FileVersionConflict)
    Public Overridable Property FileVersionConflictRequests() As DbSet(Of FileVersionConflictRequest)
    Public Overridable Property FileVersionConflictRequestStatus() As DbSet(Of FileVersionConflictRequestStatu)
    Public Overridable Property FileVersionConflictTypes() As DbSet(Of FileVersionConflictType)
    Public Overridable Property GroupFileEntryPermissions() As DbSet(Of GroupFileEntryPermission)
    Public Overridable Property Groups() As DbSet(Of Group)
    Public Overridable Property LocalShares() As DbSet(Of LocalShare)
    Public Overridable Property Permissions() As DbSet(Of Permission)
    Public Overridable Property Tags() As DbSet(Of Tag)
    Public Overridable Property TagTypes() As DbSet(Of TagType)
    Public Overridable Property UserDomains() As DbSet(Of UserDomain)
    Public Overridable Property UserFileEntryPermissions() As DbSet(Of UserFileEntryPermission)
    Public Overridable Property UserGroupAssignments() As DbSet(Of UserGroupAssignment)
    Public Overridable Property UserMappings() As DbSet(Of UserMapping)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property WorkSpaces() As DbSet(Of WorkSpace)
    Public Overridable Property CheckinSources() As DbSet(Of CheckinSource)
    Public Overridable Property ConflictResolutionModes() As DbSet(Of ConflictResolutionMode)
    Public Overridable Property FileConflicts() As DbSet(Of FileConflict)
    Public Overridable Property FileConflictFiles() As DbSet(Of FileConflictFile)
    Public Overridable Property FileHandles() As DbSet(Of FileHandle)
    Public Overridable Property FileVersionThruClouds() As DbSet(Of FileVersionThruCloud)
    Public Overridable Property FileEntryDeleteGroupHierarchies() As DbSet(Of FileEntryDeleteGroupHierarchy)
    Public Overridable Property FileShareDirs() As DbSet(Of FileShareDir)
    Public Overridable Property FileEntryDeleteGroups() As DbSet(Of FileEntryDeleteGroup)

    <DbFunction("FileMinisterEntities", "GetAllFileEntryLinks")>
    Public Overridable Function GetAllFileEntryLinks(fileEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetAllFileEntryLinks_Result)
        Dim fileEntryIdParameter As ObjectParameter = If(fileEntryId.HasValue, New ObjectParameter("FileEntryId", fileEntryId), New ObjectParameter("FileEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetAllFileEntryLinks_Result)("[FileMinisterEntities].[GetAllFileEntryLinks](@FileEntryId)", fileEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetAllSharesForUser")>
    Public Overridable Function GetAllSharesForUser(userId As Nullable(Of System.Guid)) As IQueryable(Of GetAllSharesForUser_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetAllSharesForUser_Result)("[FileMinisterEntities].[GetAllSharesForUser](@UserId)", userIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetFileEntryChildrenHierarchyInclDeleted")>
    Public Overridable Function GetFileEntryChildrenHierarchyInclDeleted(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetFileEntryChildrenHierarchyInclDeleted_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileEntryChildrenHierarchyInclDeleted_Result)("[FileMinisterEntities].[GetFileEntryChildrenHierarchyInclDeleted](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetFileEntryShare")>
    Public Overridable Function GetFileEntryShare(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetFileEntryShare_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileEntryShare_Result)("[FileMinisterEntities].[GetFileEntryShare](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestChildrenFileVersion")>
    Public Overridable Function GetLatestChildrenFileVersion(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestChildrenFileVersion_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestChildrenFileVersion_Result)("[FileMinisterEntities].[GetLatestChildrenFileVersion](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersion")>
    Public Overridable Function GetLatestFileVersion(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersion_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersion_Result)("[FileMinisterEntities].[GetLatestFileVersion](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionByPath")>
    Public Overridable Function GetLatestFileVersionByPath(relativePath As String, sharedId As Nullable(Of Short)) As IQueryable(Of GetLatestFileVersionByPath_Result)
        Dim relativePathParameter As ObjectParameter = If(relativePath IsNot Nothing, New ObjectParameter("RelativePath", relativePath), New ObjectParameter("RelativePath", GetType(String)))

        Dim sharedIdParameter As ObjectParameter = If(sharedId.HasValue, New ObjectParameter("SharedId", sharedId), New ObjectParameter("SharedId", GetType(Short)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionByPath_Result)("[FileMinisterEntities].[GetLatestFileVersionByPath](@RelativePath, @SharedId)", relativePathParameter, sharedIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionChildrenHierarchy")>
    Public Overridable Function GetLatestFileVersionChildrenHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionChildrenHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionChildrenHierarchy_Result)("[FileMinisterEntities].[GetLatestFileVersionChildrenHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionChildrens")>
    Public Overridable Function GetLatestFileVersionChildrens(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionChildrens_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionChildrens_Result)("[FileMinisterEntities].[GetLatestFileVersionChildrens](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionChildrenWithPermission")>
    Public Overridable Function GetLatestFileVersionChildrenWithPermission(fileSystemEntryId As Nullable(Of System.Guid), userId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionChildrenWithPermission_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionChildrenWithPermission_Result)("[FileMinisterEntities].[GetLatestFileVersionChildrenWithPermission](@FileSystemEntryId, @UserId)", fileSystemEntryIdParameter, userIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionParentHierarchy")>
    Public Overridable Function GetLatestFileVersionParentHierarchy(fileEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionParentHierarchy_Result)
        Dim fileEntryIdParameter As ObjectParameter = If(fileEntryId.HasValue, New ObjectParameter("FileEntryId", fileEntryId), New ObjectParameter("FileEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionParentHierarchy_Result)("[FileMinisterEntities].[GetLatestFileVersionParentHierarchy](@FileEntryId)", fileEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileVersionParentHierarchy")>
    Public Overridable Function GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileVersionParentHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileVersionParentHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileVersionParentHierarchy_Result)("[FileMinisterEntities].[GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileVersionParentHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    Public Overridable Function usp_SEL_FileSearch(startFileId As Nullable(Of System.Guid), fileName As String, isAdvancedSearch As Nullable(Of Boolean)) As Integer
        Dim startFileIdParameter As ObjectParameter = If(startFileId.HasValue, New ObjectParameter("StartFileId", startFileId), New ObjectParameter("StartFileId", GetType(System.Guid)))

        Dim fileNameParameter As ObjectParameter = If(fileName IsNot Nothing, New ObjectParameter("FileName", fileName), New ObjectParameter("FileName", GetType(String)))

        Dim isAdvancedSearchParameter As ObjectParameter = If(isAdvancedSearch.HasValue, New ObjectParameter("IsAdvancedSearch", isAdvancedSearch), New ObjectParameter("IsAdvancedSearch", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_SEL_FileSearch", startFileIdParameter, fileNameParameter, isAdvancedSearchParameter)
    End Function

    Public Overridable Function usp_SEL_GetCheckedoutFiles(userId As Nullable(Of System.Guid), shareId As Nullable(Of Integer)) As ObjectResult(Of usp_SEL_GetCheckedoutFiles_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_SEL_GetCheckedoutFiles_Result)("usp_SEL_GetCheckedoutFiles", userIdParameter, shareIdParameter)
    End Function

    Public Overridable Function usp_SEL_GetCheckinFiles(userId As Nullable(Of System.Guid), shareId As Nullable(Of Integer), fromdate As Nullable(Of Date), todate As Nullable(Of Date)) As ObjectResult(Of usp_SEL_GetCheckinFiles_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Dim fromdateParameter As ObjectParameter = If(fromdate.HasValue, New ObjectParameter("Fromdate", fromdate), New ObjectParameter("Fromdate", GetType(Date)))

        Dim todateParameter As ObjectParameter = If(todate.HasValue, New ObjectParameter("Todate", todate), New ObjectParameter("Todate", GetType(Date)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of usp_SEL_GetCheckinFiles_Result)("usp_SEL_GetCheckinFiles", userIdParameter, shareIdParameter, fromdateParameter, todateParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionDeletedChildrenWithPermission")>
    Public Overridable Function GetLatestFileVersionDeletedChildrenWithPermission(fileSystemEntryId As Nullable(Of System.Guid), userId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionDeletedChildrenWithPermission_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionDeletedChildrenWithPermission_Result)("[FileMinisterEntities].[GetLatestFileVersionDeletedChildrenWithPermission](@FileSystemEntryId, @UserId)", fileSystemEntryIdParameter, userIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetFileEntryDeleteGroupHierarchies")>
    Public Overridable Function GetFileEntryDeleteGroupHierarchies(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetFileEntryDeleteGroupHierarchies_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileEntryDeleteGroupHierarchies_Result)("[FileMinisterEntities].[GetFileEntryDeleteGroupHierarchies](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetLatestFileVersionDeletedParentHierarchy")>
    Public Overridable Function GetLatestFileVersionDeletedParentHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileVersionDeletedParentHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileVersionDeletedParentHierarchy_Result)("[FileMinisterEntities].[GetLatestFileVersionDeletedParentHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetGroupPermissionMatrixOnLatestFileVersionParentHierarchy")>
    Public Overridable Function GetGroupPermissionMatrixOnLatestFileVersionParentHierarchy(groupId As Nullable(Of System.Guid), fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetGroupPermissionMatrixOnLatestFileVersionParentHierarchy_Result)
        Dim groupIdParameter As ObjectParameter = If(groupId.HasValue, New ObjectParameter("GroupId", groupId), New ObjectParameter("GroupId", GetType(System.Guid)))

        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetGroupPermissionMatrixOnLatestFileVersionParentHierarchy_Result)("[FileMinisterEntities].[GetGroupPermissionMatrixOnLatestFileVersionParentHierarchy](@GroupId, @FileSystemEntryId)", groupIdParameter, fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterEntities", "GetUserPermissionMatrixOnLatestFileVersionParentHierarchy")>
    Public Overridable Function GetUserPermissionMatrixOnLatestFileVersionParentHierarchy(userId As Nullable(Of System.Guid), fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetUserPermissionMatrixOnLatestFileVersionParentHierarchy_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetUserPermissionMatrixOnLatestFileVersionParentHierarchy_Result)("[FileMinisterEntities].[GetUserPermissionMatrixOnLatestFileVersionParentHierarchy](@UserId, @FileSystemEntryId)", userIdParameter, fileSystemEntryIdParameter)
    End Function

End Class
