'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileVersionThruCloud
    Public Property FileVersionThruCloud1 As Integer
    Public Property TenantID As System.Guid
    Public Property FileVersionId As System.Guid
    Public Property FileHandleId As Integer

    Public Overridable Property FileHandle As FileHandle
    Public Overridable Property FileVersion As FileVersion

End Class
