'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileHandle
    Public Property FileHandleId As Integer
    Public Property TenantID As System.Guid
    Public Property FileEntryId As System.Guid
    Public Property WorkSpaceId As System.Guid
    Public Property UserId As Nullable(Of System.Guid)
    Public Property OpenedAt As Date
    Public Property ClosedAt As Nullable(Of Date)
    Public Property ServerFileSizeAtOpen As Integer
    Public Property ServerFileTimeAtOpen As Date
    Public Property ServerFileSizeAtClose As Nullable(Of Integer)
    Public Property ServerFileTimeAtClose As Nullable(Of Date)
    Public Property ToBePrcessed As String
    Public Property FileRelativePath As String

    Public Overridable Property WorkSpace As WorkSpace
    Public Overridable Property FileVersionThruClouds As ICollection(Of FileVersionThruCloud) = New HashSet(Of FileVersionThruCloud)

End Class
