'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileVersion
    Public Property FileVersionId As System.Guid
    Public Property TenantID As System.Guid
    Public Property ParentFileEntryId As System.Guid
    Public Property FileEntryId As System.Guid
    Public Property VersionNumber As Integer
    Public Property PreviousFileVersionId As Nullable(Of System.Guid)
    Public Property FileEntrySize As Long
    Public Property FileEntryName As String
    Public Property FileEntryExtension As String
    Public Property FileEntryRelativePath As String
    Public Property FileEntryHash As String
    Public Property ServerFileName As Nullable(Of System.Guid)
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property FileEntryNameWithExtension As String
    Public Property CheckInSourceId As Nullable(Of Integer)

    Public Overridable Property FileEntry As FileEntry
    Public Overridable Property FileEntry1 As FileEntry
    Public Overridable Property FileVersionConflicts As ICollection(Of FileVersionConflict) = New HashSet(Of FileVersionConflict)
    Public Overridable Property FileVersion1 As ICollection(Of FileVersion) = New HashSet(Of FileVersion)
    Public Overridable Property FileVersion2 As FileVersion
    Public Overridable Property CheckinSource As CheckinSource
    Public Overridable Property FileVersionThruClouds As ICollection(Of FileVersionThruCloud) = New HashSet(Of FileVersionThruCloud)

End Class
