'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileConflictFile
    Public Property FileConflictFileId As Integer
    Public Property TenantID As System.Guid
    Public Property FileConflictId As Integer
    Public Property ConflictFileName As String
    Public Property ConflictFilePath As String
    Public Property CreatedAt As Date
    Public Property IsUsedForResolution As Nullable(Of Boolean)
    Public Property DeletedAt As Nullable(Of Date)

    Public Overridable Property FileConflict As FileConflict

End Class
