'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileVersionConflict
    Public Property FileVersionConflictId As System.Guid
    Public Property TenantID As System.Guid
    Public Property FileEntryId As System.Guid
    Public Property FileVersionId As System.Guid
    Public Property FileVersionConflictTypeId As Byte
    Public Property UserId As System.Guid
    Public Property WorkSpaceId As System.Guid
    Public Property FileEntryPath As String
    Public Property FileEntryNameAndExtension As String
    Public Property IsResolved As Boolean
    Public Property IsActionTaken As Boolean
    Public Property IsUploadRequested As Boolean
    Public Property ResolvedByUserId As Nullable(Of System.Guid)
    Public Property ResolvedOnUTC As Nullable(Of Date)
    Public Property ResolvedType As String
    Public Property CreatedOnUTC As Date

    Public Overridable Property FileEntry As FileEntry
    Public Overridable Property FileVersion As FileVersion
    Public Overridable Property FileVersionConflictRequest As FileVersionConflictRequest
    Public Overridable Property FileVersionConflictType As FileVersionConflictType

End Class
