'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileConflict
    Public Property FileConflictId As Integer
    Public Property TenantID As System.Guid
    Public Property FileEntryId As System.Guid
    Public Property CreatedAt As Date
    Public Property ConflictResolvedTime As Nullable(Of Date)
    Public Property ResolvedBy As Nullable(Of System.Guid)
    Public Property ConflictResolutionModeId As Nullable(Of Integer)

    Public Overridable Property ConflictResolutionMode As ConflictResolutionMode
    Public Overridable Property FileEntry As FileEntry
    Public Overridable Property FileConflictFiles As ICollection(Of FileConflictFile) = New HashSet(Of FileConflictFile)

End Class
