'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Group
    Public Property GroupId As System.Guid
    Public Property TenantID As System.Guid
    Public Property GroupName As String
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property RoleID As Nullable(Of Integer)

    Public Overridable Property UserGroupAssignments As ICollection(Of UserGroupAssignment) = New HashSet(Of UserGroupAssignment)

End Class
