'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LocalShare
    Public Property LocalShareId As Integer
    Public Property TenantID As System.Guid
    Public Property FileShareId As Integer
    Public Property WorkSpaceId As System.Guid
    Public Property SharePathUNC As String
    Public Property SharePathLocal As String
    Public Property WindowsUser As String
    Public Property Password As String
    Public Property LastSyncedUTC As Nullable(Of Date)
    Public Property CreatedOnUTC As Date
    Public Property IndexServerCatalog As String

    Public Overridable Property FileShare As FileShare
    Public Overridable Property WorkSpace As WorkSpace

End Class
