'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Permission
    Public Property PermissionId As Byte
    Public Property PermissionBitValue As Byte
    Public Property PermissionName As String
    Public Property FileEntryTypeId As Byte

    Public Overridable Property FileEntryType As FileEntryType

End Class
