'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserId As System.Guid
    Public Property TenantID As System.Guid
    Public Property UserName As String
    Public Property FullName As String
    Public Property RoleId As Integer
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property LastLogin As Nullable(Of Date)
    Public Property DefaultAppCode As String

    Public Overridable Property UserGroupAssignments As ICollection(Of UserGroupAssignment) = New HashSet(Of UserGroupAssignment)

End Class
