'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserMapping
    Public Property UserMappingID As Integer
    Public Property TenantID As System.Guid
    Public Property UserDomainID As Nullable(Of Integer)
    Public Property UserID As Nullable(Of System.Guid)
    Public Property SID As String
    Public Property LoginName As String
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property GroupID As Nullable(Of System.Guid)

    Public Overridable Property UserDomain As UserDomain

End Class
