'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserDomain
    Public Property UserDomainId As Integer
    Public Property TenantID As System.Guid
    Public Property DomainName As String
    Public Property PDCServer As String
    Public Property BDCServer As String
    Public Property CreatedOnUTC As Date

    Public Overridable Property UserMappings As ICollection(Of UserMapping) = New HashSet(Of UserMapping)
    Public Overridable Property WorkSpaces As ICollection(Of WorkSpace) = New HashSet(Of WorkSpace)

End Class
