'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WorkSpace
    Public Property WorkSpaceId As System.Guid
    Public Property TenantID As System.Guid
    Public Property FileAgentId As System.Guid
    Public Property MacAddresses As String
    Public Property UserDomainId As Integer
    Public Property ServerName As String
    Public Property LastLoggedInUTC As Nullable(Of Date)
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property IndexServerName As String
    Public Property IndexServerUserName As String
    Public Property IndexServerPassword As String

    Public Overridable Property FileAgent As FileAgent
    Public Overridable Property LocalShares As ICollection(Of LocalShare) = New HashSet(Of LocalShare)
    Public Overridable Property UserDomain As UserDomain
    Public Overridable Property FileHandles As ICollection(Of FileHandle) = New HashSet(Of FileHandle)

End Class
