'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class AgentShare
    Public Property AgentShareId As Integer
    Public Property AgentId As System.Guid
    Public Property ShareId As Integer
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As System.Guid

End Class
