'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DeltaOperation
    Public Property DeltaOperationId As System.Guid
    Public Property FileSystemEntryId As System.Guid
    Public Property FileSystemEntryVersionId As System.Guid
    Public Property FileSystemEntryStatusId As Nullable(Of Byte)
    Public Property LocalFileSystemEntryName As String
    Public Property LocalFileSystemEntryExtension As String
    Public Property LocalCreatedOnUTC As Nullable(Of Date)
    Public Property IsOpen As Boolean
    Public Property IsConflicted As Boolean
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)

    Public Overridable Property FileSystemEntry As FileSystemEntry
    Public Overridable Property FileSystemEntryStatus As FileSystemEntryStatus
    Public Overridable Property FileSystemEntryVersion As FileSystemEntryVersion

End Class
