'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileSystemEntryStatus
    Public Property FileSystemEntryStatusId As Byte
    Public Property FileSystemEntryStatusName As String
    Public Property FileSystemEntryStatusDisplayName As String
    Public Property PresenceFlag As Byte

    Public Overridable Property DeltaOperations As ICollection(Of DeltaOperation) = New HashSet(Of DeltaOperation)

End Class
