'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FileMinisterClientEntities
    Inherits DbContext

    Public Sub New(connstr As String)
        MyBase.New(connstr)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property ApplicationSettings() As DbSet(Of ApplicationSetting)
    Public Overridable Property DeltaOperations() As DbSet(Of DeltaOperation)
    Public Overridable Property FileSystemEntries() As DbSet(Of FileSystemEntry)
    Public Overridable Property FileSystemEntryLinks() As DbSet(Of FileSystemEntryLink)
    Public Overridable Property FileSystemEntryStatuses() As DbSet(Of FileSystemEntryStatus)
    Public Overridable Property FileSystemEntryTypes() As DbSet(Of FileSystemEntryType)
    Public Overridable Property FileSystemEntryVersionConflicts() As DbSet(Of FileSystemEntryVersionConflict)
    Public Overridable Property FileSystemEntryVersionConflictTypes() As DbSet(Of FileSystemEntryVersionConflictType)
    Public Overridable Property FileSystemEntryVersions() As DbSet(Of FileSystemEntryVersion)
    Public Overridable Property GroupFileSystemEntryPermissionAssignments() As DbSet(Of GroupFileSystemEntryPermissionAssignment)
    Public Overridable Property Groups() As DbSet(Of Group)
    Public Overridable Property Permissions() As DbSet(Of Permission)
    Public Overridable Property Shares() As DbSet(Of Share)
    Public Overridable Property Tags() As DbSet(Of Tag)
    Public Overridable Property TagTypes() As DbSet(Of TagType)
    Public Overridable Property UserFileSystemEntryPermissionAssignments() As DbSet(Of UserFileSystemEntryPermissionAssignment)
    Public Overridable Property UserGroupAssignments() As DbSet(Of UserGroupAssignment)
    Public Overridable Property Users() As DbSet(Of User)
    Public Overridable Property RelativePathsExcludedFromSyncs() As DbSet(Of RelativePathsExcludedFromSync)

    <DbFunction("FileMinisterClientEntities", "GetAllFileSystemEntryLinks")>
    Public Overridable Function GetAllFileSystemEntryLinks(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetAllFileSystemEntryLinks_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetAllFileSystemEntryLinks_Result)("[FileMinisterClientEntities].[GetAllFileSystemEntryLinks](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetAllLatestFileVersionsWithClientPresenceForShare")>
    Public Overridable Function GetAllLatestFileVersionsWithClientPresenceForShare(shareId As Nullable(Of Integer), includeDeleted As Nullable(Of Boolean), userId As Nullable(Of System.Guid)) As IQueryable(Of GetAllLatestFileVersionsWithClientPresenceForShare_Result)
        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Dim includeDeletedParameter As ObjectParameter = If(includeDeleted.HasValue, New ObjectParameter("IncludeDeleted", includeDeleted), New ObjectParameter("IncludeDeleted", GetType(Boolean)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetAllLatestFileVersionsWithClientPresenceForShare_Result)("[FileMinisterClientEntities].[GetAllLatestFileVersionsWithClientPresenceForShare](@ShareId, @IncludeDeleted, @UserId)", shareIdParameter, includeDeletedParameter, userIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetFileSystemEntryChildrenHierarchyInclDeleted")>
    Public Overridable Function GetFileSystemEntryChildrenHierarchyInclDeleted(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetFileSystemEntryChildrenHierarchyInclDeleted_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileSystemEntryChildrenHierarchyInclDeleted_Result)("[FileMinisterClientEntities].[GetFileSystemEntryChildrenHierarchyInclDeleted](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetFileSystemEntryForCheckout")>
    Public Overridable Function GetFileSystemEntryForCheckout(shareId As Nullable(Of Integer), records As Nullable(Of Integer), userId As Nullable(Of System.Guid), workSpaceId As Nullable(Of System.Guid)) As IQueryable(Of GetFileSystemEntryForCheckout_Result)
        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Dim recordsParameter As ObjectParameter = If(records.HasValue, New ObjectParameter("Records", records), New ObjectParameter("Records", GetType(Integer)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim workSpaceIdParameter As ObjectParameter = If(workSpaceId.HasValue, New ObjectParameter("WorkSpaceId", workSpaceId), New ObjectParameter("WorkSpaceId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileSystemEntryForCheckout_Result)("[FileMinisterClientEntities].[GetFileSystemEntryForCheckout](@ShareId, @Records, @UserId, @WorkSpaceId)", shareIdParameter, recordsParameter, userIdParameter, workSpaceIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetFileSystemEntryShare")>
    Public Overridable Function GetFileSystemEntryShare(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetFileSystemEntryShare_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileSystemEntryShare_Result)("[FileMinisterClientEntities].[GetFileSystemEntryShare](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetFileSystemEntryVersionForCheckIn")>
    Public Overridable Function GetFileSystemEntryVersionForCheckIn(shareId As Nullable(Of Integer), userId As Nullable(Of System.Guid), records As Nullable(Of Integer)) As IQueryable(Of GetFileSystemEntryVersionForCheckIn_Result)
        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim recordsParameter As ObjectParameter = If(records.HasValue, New ObjectParameter("Records", records), New ObjectParameter("Records", GetType(Integer)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileSystemEntryVersionForCheckIn_Result)("[FileMinisterClientEntities].[GetFileSystemEntryVersionForCheckIn](@ShareId, @UserId, @Records)", shareIdParameter, userIdParameter, recordsParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetFileSystemEntryVersionForUpload")>
    Public Overridable Function GetFileSystemEntryVersionForUpload(shareId As Nullable(Of Integer), dateTime As Nullable(Of Date), userId As Nullable(Of System.Guid), records As Nullable(Of Integer)) As IQueryable(Of GetFileSystemEntryVersionForUpload_Result)
        Dim shareIdParameter As ObjectParameter = If(shareId.HasValue, New ObjectParameter("ShareId", shareId), New ObjectParameter("ShareId", GetType(Integer)))

        Dim dateTimeParameter As ObjectParameter = If(dateTime.HasValue, New ObjectParameter("DateTime", dateTime), New ObjectParameter("DateTime", GetType(Date)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim recordsParameter As ObjectParameter = If(records.HasValue, New ObjectParameter("Records", records), New ObjectParameter("Records", GetType(Integer)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetFileSystemEntryVersionForUpload_Result)("[FileMinisterClientEntities].[GetFileSystemEntryVersionForUpload](@ShareId, @DateTime, @UserId, @Records)", shareIdParameter, dateTimeParameter, userIdParameter, recordsParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetGroupPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy")>
    Public Overridable Function GetGroupPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy(groupId As Nullable(Of System.Guid), fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetGroupPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy_Result)
        Dim groupIdParameter As ObjectParameter = If(groupId.HasValue, New ObjectParameter("GroupId", groupId), New ObjectParameter("GroupId", GetType(System.Guid)))

        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetGroupPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy_Result)("[FileMinisterClientEntities].[GetGroupPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy](@GroupId, @FileSystemEntryId)", groupIdParameter, fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestChildrenFileSystemEntryVersions")>
    Public Overridable Function GetLatestChildrenFileSystemEntryVersions(fileSystemEntryId As Nullable(Of System.Guid), includeDeleted As Nullable(Of Boolean)) As IQueryable(Of GetLatestChildrenFileSystemEntryVersions_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim includeDeletedParameter As ObjectParameter = If(includeDeleted.HasValue, New ObjectParameter("IncludeDeleted", includeDeleted), New ObjectParameter("IncludeDeleted", GetType(Boolean)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestChildrenFileSystemEntryVersions_Result)("[FileMinisterClientEntities].[GetLatestChildrenFileSystemEntryVersions](@FileSystemEntryId, @IncludeDeleted)", fileSystemEntryIdParameter, includeDeletedParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersion")>
    Public Overridable Function GetLatestFileSystemEntryVersion(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileSystemEntryVersion_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersion_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersion](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionByPath")>
    Public Overridable Function GetLatestFileSystemEntryVersionByPath(relativePath As String, sharedId As Nullable(Of Short)) As IQueryable(Of GetLatestFileSystemEntryVersionByPath_Result)
        Dim relativePathParameter As ObjectParameter = If(relativePath IsNot Nothing, New ObjectParameter("RelativePath", relativePath), New ObjectParameter("RelativePath", GetType(String)))

        Dim sharedIdParameter As ObjectParameter = If(sharedId.HasValue, New ObjectParameter("SharedId", sharedId), New ObjectParameter("SharedId", GetType(Short)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionByPath_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionByPath](@RelativePath, @SharedId)", relativePathParameter, sharedIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionByPathAndClientPresenceFlag")>
    Public Overridable Function GetLatestFileSystemEntryVersionByPathAndClientPresenceFlag(relativePath As String, sharedId As Nullable(Of Short), checkClientPresence As Nullable(Of Boolean)) As IQueryable(Of GetLatestFileSystemEntryVersionByPathAndClientPresenceFlag_Result)
        Dim relativePathParameter As ObjectParameter = If(relativePath IsNot Nothing, New ObjectParameter("RelativePath", relativePath), New ObjectParameter("RelativePath", GetType(String)))

        Dim sharedIdParameter As ObjectParameter = If(sharedId.HasValue, New ObjectParameter("SharedId", sharedId), New ObjectParameter("SharedId", GetType(Short)))

        Dim checkClientPresenceParameter As ObjectParameter = If(checkClientPresence.HasValue, New ObjectParameter("CheckClientPresence", checkClientPresence), New ObjectParameter("CheckClientPresence", GetType(Boolean)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionByPathAndClientPresenceFlag_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionByPathAndClientPresenceFlag](@RelativePath, @SharedId, @CheckClientPresence)", relativePathParameter, sharedIdParameter, checkClientPresenceParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionClient")>
    Public Overridable Function GetLatestFileSystemEntryVersionClient(fileSystemEntryId As Nullable(Of System.Guid), includeDeleted As Nullable(Of Boolean)) As IQueryable(Of GetLatestFileSystemEntryVersionClient_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim includeDeletedParameter As ObjectParameter = If(includeDeleted.HasValue, New ObjectParameter("IncludeDeleted", includeDeleted), New ObjectParameter("IncludeDeleted", GetType(Boolean)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionClient_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionClient](@FileSystemEntryId, @IncludeDeleted)", fileSystemEntryIdParameter, includeDeletedParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionDownloadedClient")>
    Public Overridable Function GetLatestFileSystemEntryVersionDownloadedClient(fileSystemEntryId As Nullable(Of System.Guid), includeDeleted As Nullable(Of Boolean)) As IQueryable(Of GetLatestFileSystemEntryVersionDownloadedClient_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim includeDeletedParameter As ObjectParameter = If(includeDeleted.HasValue, New ObjectParameter("IncludeDeleted", includeDeleted), New ObjectParameter("IncludeDeleted", GetType(Boolean)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionDownloadedClient_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionDownloadedClient](@FileSystemEntryId, @IncludeDeleted)", fileSystemEntryIdParameter, includeDeletedParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionParentHierarchyClient")>
    Public Overridable Function GetLatestFileSystemEntryVersionParentHierarchyClient(fileSystemEntryId As Nullable(Of System.Guid), includeDeleted As Nullable(Of Boolean)) As IQueryable(Of GetLatestFileSystemEntryVersionParentHierarchyClient_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim includeDeletedParameter As ObjectParameter = If(includeDeleted.HasValue, New ObjectParameter("IncludeDeleted", includeDeleted), New ObjectParameter("IncludeDeleted", GetType(Boolean)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionParentHierarchyClient_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionParentHierarchyClient](@FileSystemEntryId, @IncludeDeleted)", fileSystemEntryIdParameter, includeDeletedParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionsChildrenHierarchy")>
    Public Overridable Function GetLatestFileSystemEntryVersionsChildrenHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileSystemEntryVersionsChildrenHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionsChildrenHierarchy_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionsChildrenHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionsChildrens")>
    Public Overridable Function GetLatestFileSystemEntryVersionsChildrens(fileSystemEntryId As Nullable(Of System.Guid), userId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileSystemEntryVersionsChildrens_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionsChildrens_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionsChildrens](@FileSystemEntryId, @UserId)", fileSystemEntryIdParameter, userIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetLatestFileSystemEntryVersionsParentHierarchy")>
    Public Overridable Function GetLatestFileSystemEntryVersionsParentHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetLatestFileSystemEntryVersionsParentHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetLatestFileSystemEntryVersionsParentHierarchy_Result)("[FileMinisterClientEntities].[GetLatestFileSystemEntryVersionsParentHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetUserPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy")>
    Public Overridable Function GetUserPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy(userId As Nullable(Of System.Guid), fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetUserPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetUserPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy_Result)("[FileMinisterClientEntities].[GetUserPermissionMatrixOnLatestFileSystemEntryVersionsParentHierarchy](@UserId, @FileSystemEntryId)", userIdParameter, fileSystemEntryIdParameter)
    End Function

    <DbFunction("FileMinisterClientEntities", "GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileSystemEntryVersionsParentHierarchy")>
    Public Overridable Function GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileSystemEntryVersionsParentHierarchy(fileSystemEntryId As Nullable(Of System.Guid)) As IQueryable(Of GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileSystemEntryVersionsParentHierarchy_Result)
        Dim fileSystemEntryIdParameter As ObjectParameter = If(fileSystemEntryId.HasValue, New ObjectParameter("FileSystemEntryId", fileSystemEntryId), New ObjectParameter("FileSystemEntryId", GetType(System.Guid)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileSystemEntryVersionsParentHierarchy_Result)("[FileMinisterClientEntities].[GetUsersAndGroupsHavingExclusivePermissionsOnLatestFileSystemEntryVersionsParentHierarchy](@FileSystemEntryId)", fileSystemEntryIdParameter)
    End Function

    Public Overridable Function usp_SEL_FileSearch(startFileId As Nullable(Of System.Guid), fileName As String, isAdvancedSearch As Nullable(Of Boolean)) As Integer
        Dim startFileIdParameter As ObjectParameter = If(startFileId.HasValue, New ObjectParameter("StartFileId", startFileId), New ObjectParameter("StartFileId", GetType(System.Guid)))

        Dim fileNameParameter As ObjectParameter = If(fileName IsNot Nothing, New ObjectParameter("FileName", fileName), New ObjectParameter("FileName", GetType(String)))

        Dim isAdvancedSearchParameter As ObjectParameter = If(isAdvancedSearch.HasValue, New ObjectParameter("IsAdvancedSearch", isAdvancedSearch), New ObjectParameter("IsAdvancedSearch", GetType(Boolean)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_SEL_FileSearch", startFileIdParameter, fileNameParameter, isAdvancedSearchParameter)
    End Function

End Class
