'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileSystemEntryVersionConflictType
    Public Property FileSystemEntryVersionConflictTypeId As Byte
    Public Property FileSystemEntryVersionConflictTypeName As String

    Public Overridable Property FileSystemEntryVersionConflicts As ICollection(Of FileSystemEntryVersionConflict) = New HashSet(Of FileSystemEntryVersionConflict)

End Class
