'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FileMinisterClientCommonEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FileMinisterClientCommonEntities")
    End Sub
    Public Sub New(strConn As String)
        MyBase.New(strConn)
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property AccountShares() As DbSet(Of AccountShare)
    Public Overridable Property AgentShares() As DbSet(Of AgentShare)
    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagram)
    Public Overridable Property UserAgents() As DbSet(Of UserAgent)
    Public Overridable Property UserShares() As DbSet(Of UserShare)
    Public Overridable Property UserAccounts() As DbSet(Of UserAccount)

    <DbFunction("FileMinisterClientCommonEntities", "GetMappedSharesForUser")>
    Public Overridable Function GetMappedSharesForUser(userId As Nullable(Of System.Guid), windowsSID As String, accountId As Nullable(Of System.Guid), roleId As Nullable(Of Byte)) As IQueryable(Of GetMappedSharesForUser_Result)
        Dim userIdParameter As ObjectParameter = If(userId.HasValue, New ObjectParameter("UserId", userId), New ObjectParameter("UserId", GetType(System.Guid)))

        Dim windowsSIDParameter As ObjectParameter = If(windowsSID IsNot Nothing, New ObjectParameter("WindowsSID", windowsSID), New ObjectParameter("WindowsSID", GetType(String)))

        Dim accountIdParameter As ObjectParameter = If(accountId.HasValue, New ObjectParameter("AccountId", accountId), New ObjectParameter("AccountId", GetType(System.Guid)))

        Dim roleIdParameter As ObjectParameter = If(roleId.HasValue, New ObjectParameter("RoleId", roleId), New ObjectParameter("RoleId", GetType(Byte)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of GetMappedSharesForUser_Result)("[FileMinisterClientCommonEntities].[GetMappedSharesForUser](@UserId, @WindowsSID, @AccountId, @RoleId)", userIdParameter, windowsSIDParameter, accountIdParameter, roleIdParameter)
    End Function

    Public Overridable Function usp_UPD_AgentShare(accountId As Nullable(Of System.Guid)) As Integer
        Dim accountIdParameter As ObjectParameter = If(accountId.HasValue, New ObjectParameter("AccountId", accountId), New ObjectParameter("AccountId", GetType(System.Guid)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction("usp_UPD_AgentShare", accountIdParameter)
    End Function

End Class
