'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileSystemEntry
    Public Property FileSystemEntryId As System.Guid
    Public Property FileSystemEntryTypeId As Byte
    Public Property ShareId As Short
    Public Property CurrentVersionNumber As Integer
    Public Property IsCheckedOut As Boolean
    Public Property CheckedOutOnUTC As Nullable(Of Date)
    Public Property CheckedOutByUserId As Nullable(Of System.Guid)
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)
    Public Property IsPermanentlyDeleted As Boolean
    Public Property PermanentlyDeletedOnUTC As Nullable(Of Date)
    Public Property PermanentlyDeletedByUserId As Nullable(Of System.Guid)
    Public Property CheckedOutWorkSpaceId As Nullable(Of System.Guid)

    Public Overridable Property DeltaOperations As ICollection(Of DeltaOperation) = New HashSet(Of DeltaOperation)
    Public Overridable Property FileSystemEntryType As FileSystemEntryType
    Public Overridable Property Share As Share
    Public Overridable Property FileSystemEntryLinks As ICollection(Of FileSystemEntryLink) = New HashSet(Of FileSystemEntryLink)
    Public Overridable Property FileSystemEntryLinks1 As ICollection(Of FileSystemEntryLink) = New HashSet(Of FileSystemEntryLink)
    Public Overridable Property FileSystemEntryVersionConflicts As ICollection(Of FileSystemEntryVersionConflict) = New HashSet(Of FileSystemEntryVersionConflict)
    Public Overridable Property FileSystemEntryVersions As ICollection(Of FileSystemEntryVersion) = New HashSet(Of FileSystemEntryVersion)
    Public Overridable Property FileSystemEntryVersions1 As ICollection(Of FileSystemEntryVersion) = New HashSet(Of FileSystemEntryVersion)
    Public Overridable Property GroupFileSystemEntryPermissionAssignments As ICollection(Of GroupFileSystemEntryPermissionAssignment) = New HashSet(Of GroupFileSystemEntryPermissionAssignment)
    Public Overridable Property Tags As ICollection(Of Tag) = New HashSet(Of Tag)
    Public Overridable Property UserFileSystemEntryPermissionAssignments As ICollection(Of UserFileSystemEntryPermissionAssignment) = New HashSet(Of UserFileSystemEntryPermissionAssignment)

End Class
