'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FileSystemEntryVersionConflict
    Public Property FileSystemEntryVersionConflictId As System.Guid
    Public Property FileSystemEntryId As System.Guid
    Public Property FileSystemEntryVersionId As System.Guid
    Public Property FileSystemEntryVersionConflictTypeId As Byte
    Public Property UserId As System.Guid
    Public Property WorkSpaceId As System.Guid
    Public Property FileSystemEntryPath As String
    Public Property FileSystemEntryNameAndExtension As String
    Public Property IsResolved As Boolean
    Public Property IsActionTaken As Boolean
    Public Property IsUploadRequested As Boolean
    Public Property ResolvedByUserId As Nullable(Of System.Guid)
    Public Property ResolvedOnUTC As Nullable(Of Date)
    Public Property ResolvedType As String
    Public Property CreatedOnUTC As Date

    Public Overridable Property FileSystemEntry As FileSystemEntry
    Public Overridable Property FileSystemEntryVersionConflictType As FileSystemEntryVersionConflictType
    Public Overridable Property FileSystemEntryVersion As FileSystemEntryVersion

End Class
