'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Tag
    Public Property TagId As System.Guid
    Public Property FileSystemEntryId As System.Guid
    Public Property TagTypeId As Byte
    Public Property TagName As String
    Public Property TagValue As String
    Public Property DisplayOrder As Byte
    Public Property CreatedOnUTC As Date
    Public Property CreatedByUserId As System.Guid
    Public Property IsDeleted As Boolean
    Public Property DeletedOnUTC As Nullable(Of Date)
    Public Property DeletedByUserId As Nullable(Of System.Guid)

    Public Overridable Property FileSystemEntry As FileSystemEntry
    Public Overridable Property TagType As TagType

End Class
