'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TagType
    Public Property TagTypeId As Byte
    Public Property TagTypeName As String

    Public Overridable Property Tags As ICollection(Of Tag) = New HashSet(Of Tag)

End Class
