'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UserAccount
    Public Property UserAccountId As Integer
    Public Property UserId As System.Guid
    Public Property AccountId As System.Guid
    Public Property AccountName As String
    Public Property RoleId As Integer
    Public Property WindowsUserSID As String
    Public Property CloudSyncServiceURL As String
    Public Property CloudSyncSyncServiceURL As String
    Public Property LocalDatabaseName As String
    Public Property AccessToken As String
    Public Property LastLoggedInUTC As Date
    Public Property WorkSpaceId As System.Guid
    Public Property CreatedOnUTC As Date
    Public Property OrganisationServiceURL As String

    Public Overridable Property UserAgents As ICollection(Of UserAgent) = New HashSet(Of UserAgent)
    Public Overridable Property UserShares As ICollection(Of UserShare) = New HashSet(Of UserShare)

End Class
