'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Runtime.Serialization

Namespace FileSyncServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SharedAccessSignatureType", [Namespace]:="http://schemas.datacontract.org/2004/07/CloudSync.SyncService")>  _
    Friend Enum SharedAccessSignatureType As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Download = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Upload = 1
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FileSyncServiceReference.IFileSyncService")>  _
    Friend Interface IFileSyncService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileSyncService/GetSharedAccessSignatureUrl", ReplyAction:="http://tempuri.org/IFileSyncService/GetSharedAccessSignatureUrlResponse")>  _
        Function GetSharedAccessSignatureUrl(ByVal ShareId As Integer, ByVal BlobName As System.Guid, ByVal SharedAccessSignatureType As FileSyncServiceReference.SharedAccessSignatureType) As System.Uri
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileSyncService/GetSharedAccessSignatureUrl", ReplyAction:="http://tempuri.org/IFileSyncService/GetSharedAccessSignatureUrlResponse")>  _
        Function GetSharedAccessSignatureUrlAsync(ByVal ShareId As Integer, ByVal BlobName As System.Guid, ByVal SharedAccessSignatureType As FileSyncServiceReference.SharedAccessSignatureType) As System.Threading.Tasks.Task(Of System.Uri)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileSyncService/DeleteBlob", ReplyAction:="http://tempuri.org/IFileSyncService/DeleteBlobResponse")>  _
        Function DeleteBlob(ByVal ShareId As Integer, ByVal BlobName As System.Guid) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IFileSyncService/DeleteBlob", ReplyAction:="http://tempuri.org/IFileSyncService/DeleteBlobResponse")>  _
        Function DeleteBlobAsync(ByVal ShareId As Integer, ByVal BlobName As System.Guid) As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Friend Interface IFileSyncServiceChannel
        Inherits FileSyncServiceReference.IFileSyncService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Friend Class FileSyncServiceClient
        Inherits System.ServiceModel.ClientBase(Of FileSyncServiceReference.IFileSyncService)
        Implements FileSyncServiceReference.IFileSyncService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetSharedAccessSignatureUrl(ByVal ShareId As Integer, ByVal BlobName As System.Guid, ByVal SharedAccessSignatureType As FileSyncServiceReference.SharedAccessSignatureType) As System.Uri Implements FileSyncServiceReference.IFileSyncService.GetSharedAccessSignatureUrl
            Return MyBase.Channel.GetSharedAccessSignatureUrl(ShareId, BlobName, SharedAccessSignatureType)
        End Function
        
        Public Function GetSharedAccessSignatureUrlAsync(ByVal ShareId As Integer, ByVal BlobName As System.Guid, ByVal SharedAccessSignatureType As FileSyncServiceReference.SharedAccessSignatureType) As System.Threading.Tasks.Task(Of System.Uri) Implements FileSyncServiceReference.IFileSyncService.GetSharedAccessSignatureUrlAsync
            Return MyBase.Channel.GetSharedAccessSignatureUrlAsync(ShareId, BlobName, SharedAccessSignatureType)
        End Function
        
        Public Function DeleteBlob(ByVal ShareId As Integer, ByVal BlobName As System.Guid) As Boolean Implements FileSyncServiceReference.IFileSyncService.DeleteBlob
            Return MyBase.Channel.DeleteBlob(ShareId, BlobName)
        End Function
        
        Public Function DeleteBlobAsync(ByVal ShareId As Integer, ByVal BlobName As System.Guid) As System.Threading.Tasks.Task(Of Boolean) Implements FileSyncServiceReference.IFileSyncService.DeleteBlobAsync
            Return MyBase.Channel.DeleteBlobAsync(ShareId, BlobName)
        End Function
    End Class
End Namespace
